export const SET_TO_LOCATION = 'SET_TO_LOCATION';
export const SET_FROM_LOCATION = 'SET_FROM_LOCATION';
export const  SET_LOCATION='SET_LOCATION'
export const  SET_ADDITIONAL_DATA='SET_ADDITIONAL_DATA'